// Copies docs/platform-terms-v1.md into packages/shared/src/platformTerms.ts so both apps can show it offline.
const fs = require('fs');
const path = require('path');
const src = path.join(__dirname, '..', 'docs', 'platform-terms-v1.md');
const out = path.join(__dirname, '..', 'packages', 'shared', 'src', 'platformTerms.ts');
const md = fs.readFileSync(src, 'utf8');
const version = (md.match(/草稿 v([\d.]+)/) || [, '1'])[1];
fs.writeFileSync(out, `// GENERATED by scripts/sync-terms.js from docs/platform-terms-v1.md — do not edit by hand.\nexport const PLATFORM_TERMS_VERSION = ${JSON.stringify(version)};\nexport const PLATFORM_TERMS_MD = ${JSON.stringify(md)};\n`);
console.log('✓ platformTerms.ts v' + version);
